import React from 'react';
import '../../styles/ImitationLearning.css';

const projects = [
  {
    title: 'Imitation Learning Robomimic',
    description:
      "This project focus on imitation learning by Robomimic training framework with Franka Emika Panda in Robosuite simulation environment.\n\nRobosuite is a simulation framework powered by the MuJoCo physics engine for robot learning. ",
    images: ['/task_lift.gif','/tool_hang.gif'] // Add video URL here
  },
  {
    title: 'How to do ? ',
    description:
      'The video below shows a teleoperation task performed in both MuJoCo and the real world to collect training data. This task helps ensure that commands in simulation and the real world are aligned, and it also contributes to reducing the sim-to-real gap.\n\nI am using Cyclone DDS to send commands from MuJoCo to the real-world Franka robot.',
    video: 'https://www.youtube.com/embed/6BnkSep1KtM'
  },
  {
    title: 'What is the problem ?(Data hungry) ',
    description:
      'To achieve good performance in both simulation and the real world, a large dataset is required. \n\nTo address this, I use MimicGen to generate additional data, significantly reducing the time needed for data collection.\n\nFor example, collecting 1,000 demonstrations manually might take around 10,000 seconds (assuming 1 demo per 10 seconds), whereas with MimicGen, providing just 10 demonstrations can result in thousands of synthetic demonstrations in a very short time—up to 1 demo per second.',
    images:['mimicgen_flow.gif']
  },
  {
    title: 'What is the problem(Sim2Real gap)',
    description:
      'The sim-to-real gap is a common challenge in imitation learning. In simulation, the environment and physics are often too idealized. To reduce this gap, I apply domain randomization to the dataset. \n\nElements such as lighting, textures, colors, camera angles, and physical properties are randomized, which significantly helps mitigate the sim-to-real gap.',
    images: ['domain_randomization.gif'],
  },
  {
    title: 'Training Result',
    description:
      'With 1,000 demonstrations generated by MimicGen and domain randomization applied, BC-RNN achieved a 100% success rate in simulation after only 20 training epochs.',
    images: ['rollout.gif'],
  },
  {
    title: 'Sim2Real progress',
    description:
      'The large sim-to-real gap remains a challenge during policy transfer. While the robot can now approach the target, it still fails to successfully grasp it. \n\nI am currently working on applying ACT or diffusion policy, along with building a more stable environment, in hopes of achieving better real-world performance.',
    images: ['sim2real.gif','robomimic_sim2real.gif',],
  },
];

const RoboticVision = () => {
  return (
    <div className="project-container">
      {projects.map((project, index) => (
        <Section
          key={index}
          title={project.title}
          description={project.description}
          mainImage={project.mainImage}
          gallery={project.gallery}
          video={project.video} // Single video
          videos={project.videos} // Multiple videos
          images={project.images} 
        />
      ))}
    </div>
  );
};

const Section = ({ title, description, mainImage, gallery, video, videos, images }) => (
  <section className="section-container">
    <div className="content-header">
      <h2>{title}</h2>
      {/* Split description into paragraphs */}
      {description.split('\n\n').map((paragraph, index) => (
        <p key={index}>{paragraph}</p>
      ))}
    </div>

    {/* Image Above Video */}
    {title === 'Control Block' && (
      <div className="image-above-video">
        <img src="/CHAMP_structure.png" alt="Gait Parameters" className="gait-image" />
      </div>
    )}

    {/* Single Video */}
    {video && (
      <div className="video-container">
        <iframe
          width="100%"
          height="400"
          src={video}
          title={`${title} Video`}
          frameBorder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        ></iframe>
      </div>
    )}

    {/*Two GIFS for human-robot Interactio*/}
    {images && (
      <div className="gif-container">
        {images.map((image, index) => (
          <img key={index} src={image} alt={`gif-${index}`} className="gif" />
        ))}
      </div>
    )}

    {/* Two Videos for VSLAM */}
    {videos && (
      <div className="videos-container">
        {videos.map((videoUrl, index) => (
          <iframe
            key={index}
            className="responsive-iframe"
            src={videoUrl}
            title={`${title} Video ${index + 1}`}
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
          ></iframe>
        ))}
      </div>
    )}

    {mainImage && (
      <div className="main-image-container">
        <img src={mainImage.src} alt={mainImage.alt} className="main-image" />
      </div>
    )}

    {gallery && (
      <div className="gallery-container">
        {gallery.map((item, index) => (
          <img key={index} src={item.src} alt={item.alt} className="gallery-image" />
        ))}
      </div>
    )}
  </section>
);

export default RoboticVision;
